import { execFile } from "node:child_process"

/**
 * Running the native PDF tools.
 *
 * Everything here shells out to a binary that parses attacker-supplied bytes,
 * so the rules are the same for all of them and are enforced in one place
 * rather than remembered at each call site:
 *
 * - **`execFile`, never `exec`.** Arguments are passed as an array and never
 *   interpolated into a shell string, so a filename cannot become a command.
 *   Paths are generated by us anyway (§9.1), but this is not the place to rely
 *   on that.
 * - **A wall clock on every invocation.** Ghostscript in particular has a long
 *   history of pathological inputs, and robustness against malformed PDFs is
 *   explicitly best-effort (design §9.2). A crafted file must not hold a
 *   request open.
 * - **An output ceiling.** A "PDF" that expands into gigabytes of stdout should
 *   fail, not exhaust the container.
 * - **A stripped environment.** No inherited credentials — the child needs
 *   `PATH` and nothing else. Ghostscript reads several `GS_*` variables that
 *   can load external resources; not passing them through is simpler than
 *   auditing them.
 */

const DEFAULT_TIMEOUT_MS = 30_000

/** Generous for a page render, nowhere near enough to exhaust the container. */
const MAX_OUTPUT_BYTES = 64 * 1024 * 1024

export type ToolResult =
  | { ok: true; stdout: Buffer }
  | { ok: false; reason: "missing" | "failed" | "timeout"; detail: string }

export async function runTool(
  command: string,
  args: string[],
  options: { timeoutMs?: number } = {}
): Promise<ToolResult> {
  return new Promise((resolve) => {
    execFile(
      command,
      args,
      {
        timeout: options.timeoutMs ?? DEFAULT_TIMEOUT_MS,
        maxBuffer: MAX_OUTPUT_BYTES,
        // Binary-safe: pdftoppm and mutool write image and PDF bytes to stdout,
        // which a string encoding would corrupt.
        encoding: "buffer",
        env: { PATH: process.env.PATH ?? "" },
        // SIGKILL rather than SIGTERM: a process wedged in a parse loop is
        // exactly the case this exists for, and it may not honour a polite ask.
        killSignal: "SIGKILL",
      },
      (error, stdout) => {
        if (!error) {
          resolve({ ok: true, stdout })
          return
        }

        const code = (error as NodeJS.ErrnoException).code

        // The binary is not installed. Distinguished from a run that failed,
        // because callers degrade differently: an absent tool is a deployment
        // gap to report, a failed run is a verdict on the file.
        if (code === "ENOENT") {
          resolve({
            ok: false,
            reason: "missing",
            detail: `${command} is not installed`,
          })
          return
        }

        if ((error as NodeJS.ErrnoException & { killed?: boolean }).killed) {
          resolve({
            ok: false,
            reason: "timeout",
            detail: `${command} timed out`,
          })
          return
        }

        resolve({ ok: false, reason: "failed", detail: error.message })
      }
    )
  })
}

/**
 * Whether a tool is present, cached for the process lifetime.
 *
 * The answer cannot change while the container runs — the binaries are baked
 * into the image — so probing once and remembering avoids an `execFile` per
 * upload just to be told the same thing.
 */
const availability = new Map<string, Promise<boolean>>()

export function isToolAvailable(command: string): Promise<boolean> {
  const cached = availability.get(command)
  if (cached) return cached

  const probe = runTool(command, ["--version"], { timeoutMs: 5_000 }).then(
    // Present but exiting non-zero on `--version` still counts as installed;
    // only ENOENT means absent. `gs` and `mutool` disagree about which flag
    // they accept, and this sidesteps caring.
    (result) => result.ok || result.reason !== "missing"
  )

  availability.set(command, probe)
  return probe
}
