export const legalPresentation = {
  home: "CodeVault",
  homeLabel: "CodeVault home",
  navigation: "Legal",
  overview: "All legal documents",
  documents: "The documents",
  introduction:
    "How we look after your data, share our work, and keep this site safe.",
  contents: "On this page",
  updated: "Last updated",
  contact: "Questions?",
  themeStorageTitle: "Your color preference",
  themeStorage:
    "If you choose a light or dark theme, we save that choice in your browser as codevault-theme. It stays on your device, is not sent to us, and can be removed by clearing this site's browser data.",
  backToTop: "Back to top",
  image: {
    src: "/legal/fjord.webp",
    srcSet: "/legal/fjord-small.webp 800w, /legal/fjord.webp 1800w",
    alt: "Weathered rock and quiet water in a Norwegian fjord",
  },
  documentsList: [
    {
      label: "Privacy",
      href: "/legal/privacy",
      description: "What we collect, how long we keep it, and your rights.",
    },
    {
      label: "Terms",
      href: "/legal/terms",
      description: "Using the archive, ownership, and what we ask of you.",
    },
    {
      label: "Cookies",
      href: "/legal/cookies",
      description: "One cookie, only if you sign in. No tracking.",
    },
    {
      label: "Security",
      href: "/legal/security",
      description: "Report a vulnerability and know what to expect.",
    },
  ],
} as const

export const site = {
  presentation: {
    home: "CodeVault home",
    aboutNavigation: "About",
    next: "Related pages",
    aboutImage: {
      src: "/stock/aperture-earth-from-orbit-window.avif",
      srcSet:
        "/stock/aperture-earth-from-orbit-window-small.webp 800w, /stock/aperture-earth-from-orbit-window.avif 2000w",
      alt: "A spacecraft cupola, its windows arranged around a view of Earth.",
    },
    aboutNext: [
      {
        label: "Who we are",
        href: "/about/who-we-are",
        description: "How we think about the work.",
      },
      {
        label: "Projects",
        href: "/projects",
        description: "What we're building and breaking.",
      },
    ],
    notFound: {
      code: "404",
      title: "Page not found",
      description: "This page may have moved or been removed.",
      action: "Back to home",
    },
  },
  name: "CodeVault",
  tagline: "We point ourselves at tech, and see what happens.",
  description:
    "CodeVault runs small projects across tech and shares the work, wrong turns, and results.",
  url: "https://codevault.no",

  /**
   * The page background at each end of the color scheme, as browser chrome
   * sees it — the `theme-color` meta pair in `__root.tsx` and the PWA
   * manifest both read from here.
   *
   * They mirror `--ivory-light` and the dark-mode `--background` in
   * `globals.css`. Duplicated out of the stylesheet because neither consumer
   * is CSS: a `<meta>` and a JSON document can't resolve a custom property.
   * Change one, change the other.
   */
  themeColor: {
    light: "#faf9f5",
    dark: "#1f1e1d",
  },

  /**
   * The social card. 1200×630 is the size Open Graph consumers crop toward,
   * and it is generated by `bun run brand:assets` alongside the favicons.
   */
  ogImage: "/og-image.png",
} as const

export const navigation = {
  label: "Main navigation",
  home: "CodeVault home",
  open: "Open navigation",
  close: "Close navigation",
  contact: "Get in touch",
  skip: "Skip to content",
  theme: "Switch color theme",
  footer: "Elsewhere in CodeVault",
  copyright: "All rights reserved.",
  sitemap: "Sitemap",
  links: [
    { label: "Projects", href: "/projects" },
    { label: "Research", href: "/research" },
    { label: "About", href: "/about" },
    { label: "Archive", href: "/reports" },
  ],
} as const

export const homePage = {
  hero: {
    title: "Security starts",
    titleAccent: "with curiosity.",
    introduction:
      "We look closely at the systems we depend on. Then build, test, and share what we learn.",
    action: "Explore our research",
    secondaryAction: "Meet the projects",
    world: {
      title: "A closer look at a connected world",
      description:
        "An architectural illustration of connected devices, a research lab, and a protected system. Signals travel between them as a boundary surrounds the central structure.",
      pause: "Pause animation",
      play: "Play animation",
      reducedMotion: "Animation paused for reduced motion",
      viewsLabel: "Explore the security illustration",
      captionLabel: "Inside the illustration",
      views: [
        {
          label: "Follow the signal",
          caption: "Every connection tells a story.",
        },
        {
          label: "Question the boundary",
          caption: "Look closely at what keeps systems apart.",
        },
        {
          label: "Share the understanding",
          caption: "Turn what we learn into something others can use.",
        },
      ],
    },
  },
  recent: {
    title: "Selected projects",
    action: "See every project",
    featured: "Latest project",
    read: "Explore the project",
    selected: ["sandbox", "orbit", "tex"],
  },
  research: {
    title: "Security research",
    description: "Look deeper. Leave things safer.",
    action: "Explore the research",
    featured: "From the research desk",
    read: "Read the finding",
  },
  process: {
    title: "Curiosity is a practice.",
    introduction:
      "Small projects. Open questions. Something learned along the way.",
    action: "About CodeVault",
  },
} as const

export const projectsPage = {
  title: "Projects",
  introduction: "What we've tried, what changed, and what came out of it.",
  metaDescription:
    "CodeVault projects, shared with the work, changes, and limits left intact.",
  featured: "In focus",
  featuredSlug: "sandbox",
  collection: "The project index",
  allFields: "All fields",
  allStatuses: "Every status",
  fieldLabel: "Filter by field",
  statusLabel: "Filter by status",
  searchLabel: "Search projects",
  searchPlaceholder: "Find something interesting",
  empty: "No projects match these filters.",
  reset: "Clear filters",
  countLabel: "projects",
  read: "Explore the project",
  back: "All projects",
  record: "Project record",
  visuals: {
    orbit: {
      signal: "Near miss",
      measure: "Closing distance",
    },
    "plant-pi": {
      reading: "Soil moisture",
      pump: "Pump",
      reservoir: "Reservoir",
    },
    "git-story": {
      input: "Git log",
      output: "The story",
    },
    seamark: {
      field: "Observed tracks",
      signal: "Review this track",
    },
    tex: {
      source: "Source",
      page: "Page",
      heading: "A smaller rebuild",
      body: "The editor parses the document before it decides what to compile.",
      emphasis: "Save only what changed.",
    },
    sandbox: {
      host: "Host",
      guest: "QEMU guest",
      network: "Restricted network",
      run: "Disposable run",
    },
  },
} as const

export const footerNav = {
  Projects: [
    { label: "All projects", href: "/projects" },
    { label: "Sandbox", href: "/projects/sandbox" },
    { label: "Orbit", href: "/projects/orbit" },
    { label: "git-story", href: "/projects/git-story" },
    { label: "The plant-watering Pi", href: "/projects/plant-pi" },
    { label: "GitHub", href: "https://github.com/CodeVault-LLC" },
  ],
  Writing: [
    { label: "Security research", href: "/research" },
    { label: "Hummingbird finding", href: "/research/hummingbird" },
    { label: "Reports archive", href: "/reports" },
  ],
  About: [
    { label: "How we work", href: "/about" },
    { label: "Who we are", href: "/about/who-we-are" },
    { label: "Get in touch", href: "/about/contact" },
    { label: "Brand", href: "/about/brand" },
  ],
  Legal: [
    { label: "Privacy", href: "/legal/privacy" },
    { label: "Terms", href: "/legal/terms" },
    { label: "Cookies", href: "/legal/cookies" },
    { label: "Security", href: "/legal/security" },
  ],
} as const

export const researchPage = {
  featured: "Latest finding",
  path: "/research",
  title: "Security research",
  image: "/research/mountain.webp",
  imageSrcSet:
    "/research/mountain-small.webp 800w, /research/mountain.webp 2400w",
  imageAlt: "Forested slopes overlooking a glacier and a wide mountain valley",
  homeLabel: "CodeVault home",
  footerLabel: "Research footer",
  disclosureLabel: "Disclosure policy",
  exploreLabel: "Explore the research",
  independentLabel: "Independent findings",
  shortPdfLabel: "Public report",
  introduction:
    "Independent vulnerability analysis. Tested findings, documented impact, and practical guidance for maintainers.",
  description:
    "Independent vulnerability research by CodeVault, with documented findings, controlled validation, and remediation guidance.",
  findingsTitle: "Published research",
  readFinding: "Read the finding",
  approachTitle: "Research process",
  approach:
    "We trace defects through source code, verify their impact in isolated environments, and report the evidence with clear remediation guidance.",
  methods: [
    {
      title: "Understand the cause",
      text: "Trace the behavior through the code and identify the conditions that make a vulnerability possible.",
    },
    {
      title: "Test the conclusion",
      text: "Validate the impact in an isolated environment. Use negative controls to distinguish a reproducible defect from an assumption.",
    },
    {
      title: "Document the result",
      text: "Record affected versions, deployment requirements, and practical remediation guidance for maintainers.",
    },
  ],
  contactTitle: "Discuss a research project",
  contactText: "Have software you would like us to investigate?",
  contactLabel: "Get in touch",
  backLabel: "All security research",
  detailsTitle: "Research record",
  timelineTitle: "Disclosure record",
  sourcesTitle: "Sources & report",
  pdfLabel: "Download public summary",
} as const

export const researchFindings = [
  {
    slug: "hummingbird",
    author: "CodeVault LLC",
    score: "9.8",
    cve: "CVE-2026-83627",
    path: "/research/hummingbird",
    title: "Unauthenticated remote code execution in Hummingbird",
    product: "Hummingbird Performance",
    report: "RPT-000001",
    reportDate: "2026-08-24",
    dateLabel: "24 August 2026",
    severity: "Critical",
    summary:
      "A page-cache debug logging defect allowed unauthenticated code execution under specific caching and logging conditions.",
    introduction:
      "CodeVault independently confirmed unauthenticated code execution in Hummingbird Performance 3.20.0 under specific caching and debug-logging conditions.",
    metadata: [
      { label: "Research by", value: "CodeVault LLC" },
      { label: "Report", value: "RPT-000001" },
      { label: "Confirmed version", value: "3.20.0" },
      { label: "CVSS 3.1", value: "9.8 · Critical", tone: "critical" },
      { label: "Related CVE", value: "CVE-2026-83627", tone: "critical" },
      { label: "Fix listed by WPScan", value: "3.21.1" },
    ],
    sections: [
      {
        id: "finding",
        title: "What we found",
        paragraphs: [
          "During early cache initialization, the debug logger could write untrusted request data into an executable log without its protective guard.",
          "The issue required local page caching and debug logging, both non-default settings, and an absent or unprotected log.",
        ],
      },
      {
        id: "validation",
        title: "What we validated",
        paragraphs: [
          "Testing of the official 3.20.0 release demonstrated code execution as the web-server account in an isolated environment, putting WordPress data and application integrity at risk.",
          "A negative control blocked the tested technique. No credential contents were read, persistence created, or destructive actions performed.",
        ],
      },
      {
        id: "remediation",
        title: "Addressing the issue",
        paragraphs: [
          "WPScan lists version 3.21.1 as the fix for its related advisory. Site owners should update affected installations and review existing debug logs as part of remediation.",
          "Keep logs non-executable, restrict direct web access, and stop logging if protective initialization fails. Handle existing logs safely during an upgrade.",
        ],
      },
      {
        id: "public-record",
        title: "The public advisory",
        paragraphs: [
          "WPScan published CVE-2026-83627 on 4 September 2026, describing a related Hummingbird page-cache logging vulnerability through cookie names. CodeVault's report documents a request-URI path through the same logging component.",
          "CodeVault tested 3.20.0. The broader affected-version range and fix in 3.21.1 are reported by WPScan.",
        ],
      },
    ],
    timeline: [
      {
        date: "2026-08-24",
        label: "24 August 2026",
        title: "CodeVault validation documented",
        text: "Reproduction completed against 3.20.0; CodeVault prepared RPT-000001.",
      },
      {
        date: "2026-08-24",
        label: "24 August 2026",
        title: "Submission recorded",
        text: "An existing Patchstack submission was recorded. Original transmission time was unavailable; a response was pending.",
      },
      {
        date: "2026-09-04",
        label: "4 September 2026",
        title: "Related advisory published",
        text: "WPScan published CVE-2026-83627, listing a fix in Hummingbird 3.21.1.",
      },
    ],
    pdf: "/research/reports/RPT-000001-public-summary.pdf",
    pdfDetail: "PDF · Public summary of RPT-000001",
    advisoryLabel: "Read the WPScan advisory",
    advisory:
      "https://wpscan.com/vulnerability/2cba25b7-9ed0-409c-a00d-bdd86fc06ed3/",
    sourceNote:
      "The public summary is based on CodeVault's vendor report dated 24 August 2026. It omits reproduction instructions and internal evidence. Advisory information was checked on 8 September 2026.",
  },
] as const
