export const site = {
  name: "CodeVault",
  tagline: "We point ourselves at tech, and see what happens.",
  description:
    "CodeVault isn't a product company. We run projects across everything in tech — trials, experiments, and the occasional small thing we push to GitHub. Built in the open, shared as they are.",
  url: "https://codevault.no",

  /**
   * The page background at each end of the color scheme, as browser chrome
   * sees it — the `theme-color` meta pair in `__root.tsx` and the PWA
   * manifest both read from here.
   *
   * They mirror `--ivory-light` and the dark-mode `--background` in
   * `globals.css`. Duplicated out of the stylesheet because neither consumer
   * is CSS: a `<meta>` and a JSON document can't resolve a custom property.
   * Change one, change the other.
   */
  themeColor: {
    light: "#faf9f5",
    dark: "#1f1e1d",
  },

  /**
   * The social card. 1200×630 is the size Open Graph consumers crop toward,
   * and it is generated by `bun run brand:assets` alongside the favicons.
   */
  ogImage: "/og-image.png",
} as const

export const projectsPage = {
  title: "Projects",
  introduction: "What we've tried, what changed, and what came out of it.",
  metaDescription:
    "CodeVault projects, shared with the work, changes, and limits left intact.",
  visuals: {
    orbit: {
      signal: "Near miss",
      measure: "Closing distance",
    },
    "plant-pi": {
      reading: "Soil moisture",
      pump: "Pump",
      reservoir: "Reservoir",
    },
    "git-story": {
      input: "Git log",
      output: "The story",
    },
    seamark: {
      field: "Observed tracks",
      signal: "Review this track",
    },
    tex: {
      source: "Source",
      page: "Page",
      heading: "A smaller rebuild",
      body: "The editor parses the document before it decides what to compile.",
      emphasis: "Save only what changed.",
    },
    sandbox: {
      host: "Host",
      guest: "QEMU guest",
      network: "Restricted network",
      run: "Disposable run",
    },
  },
} as const

export type NavItem = {
  label: string
  href?: string
  description?: string
  sections?: { heading: string; links: { label: string; href: string }[] }[]
}

export const mainNav: NavItem[] = [
  {
    label: "Projects",
    description: "The things we're building, breaking, and learning from.",
    sections: [
      {
        heading: "Recent",
        links: [
          { label: "Sandbox", href: "/projects/sandbox" },
          { label: "Orbit", href: "/projects/orbit" },
          { label: "git-story", href: "/projects/git-story" },
          { label: "All projects", href: "/projects" },
        ],
      },
      {
        heading: "In the open",
        links: [
          { label: "GitHub", href: "https://github.com/CodeVault-LLC" },
          { label: "Experiments", href: "/projects" },
          { label: "Changelog", href: "/projects/git-story" },
        ],
      },
    ],
  },
  {
    label: "About",
    description: "Who we are and how we work.",
    sections: [
      {
        heading: "CodeVault",
        links: [
          { label: "How we work", href: "/about" },
          { label: "Who we are", href: "/about/who-we-are" },
          { label: "Get in touch", href: "/about/contact" },
          { label: "Brand", href: "/about/brand" },
        ],
      },
    ],
  },
]

export const releases: {
  title: string
  description: string
  date: string
  category: string
  href: string
}[] = [
  {
    title: "A guest shell for work that should not touch the host",
    description:
      "A QEMU sandbox for AI-assisted security work, with deny-by-default networking and the unfinished boundaries shown plainly.",
    date: "August 22, 2026",
    category: "Security project",
    href: "/projects/sandbox",
  },
  {
    title: "Orbit — a tiny game we built in a weekend",
    description:
      "A browser game about keeping satellites from colliding. It does a few basic things, and we learned a lot shipping it.",
    date: "June 12, 2026",
    category: "Experiment",
    href: "/projects/orbit",
  },
  {
    title: "A CLI that turns your git log into a story",
    description:
      "We wanted our commit history to read better, so we made a small tool. Now it's on GitHub for anyone who wants it.",
    date: "May 28, 2026",
    category: "Open source",
    href: "/projects/git-story",
  },
]

export const footerNav = {
  Projects: [
    { label: "All projects", href: "/projects" },
    { label: "Sandbox", href: "/projects/sandbox" },
    { label: "Orbit", href: "/projects/orbit" },
    { label: "git-story", href: "/projects/git-story" },
    { label: "The plant-watering Pi", href: "/projects/plant-pi" },
    { label: "GitHub", href: "https://github.com/CodeVault-LLC" },
  ],
  Writing: [
    { label: "Blog", href: "#blog" },
    { label: "Project logs", href: "#releases" },
    { label: "Notes", href: "#blog" },
    { label: "Changelog", href: "#releases" },
    { label: "Community", href: "#community" },
  ],
  About: [
    { label: "How we work", href: "/about" },
    { label: "Who we are", href: "/about/who-we-are" },
    { label: "Get in touch", href: "/about/contact" },
    { label: "Brand", href: "/about/brand" },
  ],
  Legal: [
    { label: "Privacy", href: "/legal/privacy" },
    { label: "Terms", href: "/legal/terms" },
    { label: "Cookies", href: "/legal/cookies" },
    { label: "Security", href: "/legal/security" },
  ],
} as const
