/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as FaqImport } from './routes/faq'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as ProductProductIdImport } from './routes/product/$productId'
import { Route as ProductProductIdIndexImport } from './routes/product/$productId.index'
import { Route as DashboardProjectsIndexImport } from './routes/dashboard/projects/index'
import { Route as ProductProductIdDocsImport } from './routes/product/$productId.docs'
import { Route as ProductProductIdCheckoutImport } from './routes/product/$productId.checkout'
import { Route as ProductProductIdDocsIndexImport } from './routes/product/$productId.docs/index'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const FaqRoute = FaqImport.update({
  path: '/faq',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const ProductProductIdRoute = ProductProductIdImport.update({
  path: '/product/$productId',
  getParentRoute: () => rootRoute,
} as any)

const ProductProductIdIndexRoute = ProductProductIdIndexImport.update({
  path: '/',
  getParentRoute: () => ProductProductIdRoute,
} as any)

const DashboardProjectsIndexRoute = DashboardProjectsIndexImport.update({
  path: '/dashboard/projects/',
  getParentRoute: () => rootRoute,
} as any)

const ProductProductIdDocsRoute = ProductProductIdDocsImport.update({
  path: '/docs',
  getParentRoute: () => ProductProductIdRoute,
} as any)

const ProductProductIdCheckoutRoute = ProductProductIdCheckoutImport.update({
  path: '/checkout',
  getParentRoute: () => ProductProductIdRoute,
} as any)

const ProductProductIdDocsIndexRoute = ProductProductIdDocsIndexImport.update({
  path: '/',
  getParentRoute: () => ProductProductIdDocsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/product/$productId/checkout': {
      id: '/product/$productId/checkout'
      path: '/checkout'
      fullPath: '/product/$productId/checkout'
      preLoaderRoute: typeof ProductProductIdCheckoutImport
      parentRoute: typeof ProductProductIdImport
    }
    '/product/$productId/docs': {
      id: '/product/$productId/docs'
      path: '/docs'
      fullPath: '/product/$productId/docs'
      preLoaderRoute: typeof ProductProductIdDocsImport
      parentRoute: typeof ProductProductIdImport
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/product/$productId/': {
      id: '/product/$productId/'
      path: '/'
      fullPath: '/product/$productId/'
      preLoaderRoute: typeof ProductProductIdIndexImport
      parentRoute: typeof ProductProductIdImport
    }
    '/product/$productId/docs/': {
      id: '/product/$productId/docs/'
      path: '/'
      fullPath: '/product/$productId/docs/'
      preLoaderRoute: typeof ProductProductIdDocsIndexImport
      parentRoute: typeof ProductProductIdDocsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  FaqRoute,
  LoginRoute,
  RegisterRoute,
  ProductProductIdRoute: ProductProductIdRoute.addChildren({
    ProductProductIdCheckoutRoute,
    ProductProductIdDocsRoute: ProductProductIdDocsRoute.addChildren({
      ProductProductIdDocsIndexRoute,
    }),
    ProductProductIdIndexRoute,
  }),
  DashboardIndexRoute,
  DashboardProjectsIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/faq",
        "/login",
        "/register",
        "/product/$productId",
        "/dashboard/",
        "/dashboard/projects/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/faq": {
      "filePath": "faq.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/product/$productId": {
      "filePath": "product/$productId.tsx",
      "children": [
        "/product/$productId/checkout",
        "/product/$productId/docs",
        "/product/$productId/"
      ]
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/product/$productId/checkout": {
      "filePath": "product/$productId.checkout.tsx",
      "parent": "/product/$productId"
    },
    "/product/$productId/docs": {
      "filePath": "product/$productId.docs.tsx",
      "parent": "/product/$productId",
      "children": [
        "/product/$productId/docs/"
      ]
    },
    "/dashboard/projects/": {
      "filePath": "dashboard/projects/index.tsx"
    },
    "/product/$productId/": {
      "filePath": "product/$productId.index.tsx",
      "parent": "/product/$productId"
    },
    "/product/$productId/docs/": {
      "filePath": "product/$productId.docs/index.tsx",
      "parent": "/product/$productId/docs"
    }
  }
}
ROUTE_MANIFEST_END */
